api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    defaults:
        pagination_enabled: true
        pagination_items_per_page: 10 # Default value
        pagination_maximum_items_per_page: 10

